ADMIN='Admin'
BROKER='Broker'
BORROWER='Borrower'
LENDER='Lender'
MORTGAGE_TYPES=["RESIDENTIAL FIXED", "RESIDENTIAL ARM", "COMMERCIAL","PRIVATE"]
BROKER_NOT_VERIFIED="not_verified"
BROKER_ON_HOLD="on_hold"
BROKER_VERIFIED="verified"
REQ_STATUS={expire:'expired', cancelled: 'cancelled',publish: 'published',draft: 'draft'}
BID_STATUS={approved: 'Approved',rejected: 'Rejected',sent:'Sent', invited: 'Invited'}
BID_MORTGAGE_TYPES=["FIXED", "VRM", "ARM"]
TERM=["3 months","6 months","12 months","24 months","36 months","48 months","5 years","5 years","7 years","10 years","15 years","20 years","25 years","30 years"]
BID_MAX_RATE=15
BID_MAX_BROKER_FEE=15
BID_MAX_LENDER_FEE=15
COINS_PER_BID=100
MAX_BIDS_PER_REQUEST=2
BID_MAX_AMORTIZATION=50
TRANSACTION_SOURCE=['stripe','bid']
TRANSACTION_TYPE=['credit','debit']